---
- hosts: all
  become: yes
  tasks:
  - name: install tree
    apt:
     name: tree
     state: present
  - name: install wget
    apt:
     name: wget
     state: present
  - name: install apache2
    apt:
     name: apache2
     state: present
  - name: start apache2 service
    service:
     name: apache2
     state: started
     enabled: yes
   
