---
- hosts: webservers
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      state: present
    when: ansible_os_family =="Debian"

  - namee: install tree
    apt:
      name: tree
      state: present
    ignore_errors: yes
    when: ansible_os_family =="Debian"

  - name: install wget
    apt:
      name: wget
      state: present
    when: ansible_os_family =="Debian"