---
- hosts: webservers
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webservers on ubuntu
    apt:
     name: apache2
     state: present
    when: ansible_os_family =="Debian"

  - name: start the webservers
    service:
     name: apache2
     state: started
    when: ansible_os_family =="Debian"

  - name: copy myindex.j2 into ansible node
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
    when: ansible_os_family =="Debian"

  